//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtConspiracy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArtPiece
    {
        public int PID { get; set; }
        public string MID { get; set; }
        public string PieceTitle { get; set; }
        public string PieceDesc { get; set; }
        public string imgURL { get; set; }
    }
}
