//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArtConspiracy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WrittenPiece
    {
        public int WID { get; set; }
        public int MID { get; set; }
        public string Title { get; set; }
        public string PieceText { get; set; }
    }
}
